### ISSUE TITLE
The URL for download minecraft .jar files is changed by mojang

### ISSUE THREAD

**Issue by GarryLai** [betrok/ttyhstore#4]
I find this tool can't use now, because all the http://s3.amazonaws.com/Minecraft.Download/ are changed to like this: https://launcher.mojang.com/mc/game/18w22c/client/ec446c24c4842f6237ba7c560a5b0dae9ac87c22/client.jar since 1.13.
I think you need to fix the API URL in main.go (it seems like you need to get the hash first)
Thanks for help :D

**Comment by betrok** [comment]
Yep, and overall format of version description has changed rather majorly. Moreover it's likely that out launcher will need some changes for 1.13 as well...

I didn't have time to update everything for now.
I will add a comment here as soon as the situation changes.

**Comment by betrok** [comment]
I updated ttyhstore, but, as I said, some changes are needed in the launcher.

**Comment by betrok** [comment]
I doubt that this is still relevant for you, but we finally finished support for the latest versions.
